numpy array and basics


In [1]:
import numpy as np

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


List vs numpy array


In [6]:
pylist = [1, 2, 3, 4, 5]
print("Python List manipulation:", pylist*2)

np_array = np.array([1, 2, 3, 4, 5])   #element-wise operations
print("Numpy Array manipulation:", np_array*2) 

import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("Python List Time:", time.time() - start)
start = time.time()
py_array = np.arange(100000)*2
print("Numpy Array Time:", time.time() - start)


Python List manipulation: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy Array manipulation: [ 2  4  6  8 10]
Python List Time: 0.00640869140625
Numpy Array Time: 0.0009462833404541016


create array from scratch


In [14]:
zeros = np.zeros((3, 4))  # Create a 3x4 array of zeros
print("Zeros Array:\n", zeros)

ones = np.ones((2, 3))    # Create a 2x3 array of ones
print("Ones Array:\n", ones)

full = np.full((2, 2), 7)  # Create a 2x2 array filled with 7
print("Full Array:\n", full)

random = np.random.random((2, 2))  # Create a 2x2 array of random floats
print("Random Array:\n", random)

sequence = np.arange(10)  # Create an array with a sequence of numbers
print("Sequence Array:", sequence)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array:
 [[7 7]
 [7 7]]
Random Array:
 [[0.53540169 0.05646189]
 [0.66913262 0.6203567 ]]
Sequence Array: [0 1 2 3 4 5 6 7 8 9]


Vector, Matrix and tensor

In [15]:
vector = np.array([1, 2, 3])  # 1D array (vector)
print("Vector:", vector)

matrix = np.array([[1, 2], [3, 4]])  # 2D array (matrix)
print("Matrix:\n", matrix)

tensor = np.array([[[1, 2], [3, 4]],
                    [[5, 6], [7, 8]]])  # 3D array (tensor)
print("Tensor:\n", tensor)

Vector: [1 2 3]
Matrix:
 [[1 2]
 [3 4]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties



In [18]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape", arr.shape)
print("dimensions", arr.ndim)
print("size", arr.size)
print("dtype", arr.dtype)

shape (2, 3)
dimensions 2
size 6
dtype int64


### Array reshaping 

In [21]:
arr = np.arange(12)
print("Original Array:", arr)

reshaped_arr = arr.reshape(3, 4)  # Reshape to 3 rows and 4 columns
print("Reshaped Array:\n", reshaped_arr)

flattened = reshaped_arr.flatten()  # Flatten the array back to 1D
print("Flattened Array:", flattened)

raveled = reshaped_arr.ravel()  # Ravel the array (similar to flatten) ( returns view, instead of copy)
print("Raveled Array:", raveled)

transpose = reshaped_arr.T  # Transpose the array
print("Transposed Array:\n", transpose)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
