### Numpy Array Operations


In [2]:
import numpy as np

In [12]:
arr = np.array([1, 2, 3, 4, 5,6,7,8,9,10])
print("basic slicing : ", arr[2:7])
print("step slicing : ", arr[1:9:2])
print("negative slicing : ", arr[-3])

basic slicing :  [3 4 5 6 7]
step slicing :  [2 4 6 8]
negative slicing :  8


In [15]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("2D array basic slicing : ", arr_2d[1:2])  # Slicing rows
print("2D array basic slicing : ", arr_2d[1,2])  # Slicing rows
print("2D array step slicing : ", arr_2d[0:3:2])  # Slicing rows with step
print("2D array negative slicing : ", arr_2d[-1])  # Last row
print("2D array slicing : ", arr_2d[1:3, 0:2])  # Slicing rows and columns
print("2d array slicing : ", arr_2d[:, 2])  # Slicing all rows for a specific column


2D array basic slicing :  [[4 5 6]]
2D array basic slicing :  6
2D array step slicing :  [[1 2 3]
 [7 8 9]]
2D array negative slicing :  [7 8 9]
2D array slicing :  [[4 5]
 [7 8]]
2d array slicing :  [3 6 9]


### Sorting

In [14]:
unsorted = np.array([3, 1, 4, 2, 5,7,6,9,8])
print("Sorted array:", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[2,1],[2,3]])
print("sorted 2d array by column: ", np.sort(arr_2d_unsorted, axis=0))  # Sort by column
print("sorted 2d array by row: ", np.sort(arr_2d_unsorted, axis=1))  # Sort by row

Sorted array: [1 2 3 4 5 6 7 8 9]
sorted 2d array by column:  [[2 1]
 [2 1]
 [3 3]]
sorted 2d array by row:  [[1 3]
 [1 2]
 [2 3]]


#### Filtering

In [3]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers:", even_numbers)

Even numbers: [ 2  4  6  8 10]


### Filter with mask

In [4]:
mask = numbers > 5
print("Numbers greater than 5:", numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


### Fancy indexing Vs np.where()

In [5]:
indices = [0, 2, 4]
print("Fancy indexing:", numbers[indices])

where_result = np.where(numbers > 5)
print("np where: ", numbers[where_result])

Fancy indexing: [1 3 5]
np where:  [ 6  7  8  9 10]


In [8]:
condition_array = np.where(numbers > 5, numbers *4 , numbers)
print("np where with condition: ", condition_array)

np where with condition:  [ 1  2  3  4  5 24 28 32 36 40]


#### Adding and removing data

In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print("Combined array:", combined)

Combined array: [1 2 3 4 5 6]


#### array compatibility 


In [10]:
a= np.array([1, 2, 3])
b = np.array([4, 5, 6])     
c = np.array([7, 8, 9])

print("Array compatibility check:", a.shape == b.shape)

Array compatibility check: True


In [15]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

modified = np.vstack((original, new_row))  # Add a new row

print("Modified array with new row and column:\n", modified)    

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))  # Add a new column
print("Modified array with new column:\n", with_new_col)





Modified array with new row and column:
 [[1 2]
 [3 4]
 [5 6]]
Modified array with new column:
 [[1 2 7]
 [3 4 8]]


In [16]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)  # Delete element at index 2
print("Array after deletion:", deleted)

Array after deletion: [1 2 4 5]
